Include <strings.h> for strcasecmp
Summary:
POSIX states [1] that it is in the <strings.h> include file, not
<string.h>. While it's likely pulled in implicitly for glibc, its
absence causes a build error with musl libc
(src/wmlib/cdrom.c:128:33: error: implicit declaration of function
'strcasecmp';).

[1] http://pubs.opengroup.org/onlinepubs/9699919799/functions/strcasecmp.html

Test Plan: Builds fine with glibc and musl libcs.

Differential Revision: https://phabricator.kde.org/D19614